FROM 32bit/ubuntu:16.04
MAINTAINER rayslava@gmail.com

RUN apt-get -qq dist-upgrade -y
RUN apt-get -qq update -y
RUN apt-get -qq --yes --force-yes install software-properties-common python-software-properties
RUN add-apt-repository --yes ppa:ubuntu-toolchain-r/test
RUN apt-get -qq update -y
# Setting up build environment
RUN apt-get -qq --yes --force-yes install gcc-7 g++-7 libgtest-dev valgrind lcov cmake cmake-data curl build-essential libtool autotools-dev automake checkinstall check git yasm pkg-config libncurses5-dev libgmp-dev
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 40 --slave /usr/bin/g++ g++ /usr/bin/g++-7
RUN update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-7 40
RUN update-alternatives --config gcc
RUN update-alternatives --config gcov
RUN cd $(mktemp -d) && cmake /usr/src/gtest &&  make -j4 && sudo mv libgtest.a libgtest_main.a /usr/lib/

# Building rapidjson
RUN cd $(mktemp -d) && git clone git://github.com/Tencent/rapidjson.git && cd rapidjson && mkdir build && cd build && cmake .. && make && checkinstall --install --pkgname rapidjson --pkgversion 1.1.0 && sudo ldconfig
# Building nettle
ARG NETTLE_VER
ENV NETTLE_VER=${NETTLE_VER:-"3.3"}
RUN cd $(mktemp -d) && curl -L "https://ftp.gnu.org/gnu/nettle/nettle-${NETTLE_VER}.tar.gz" | tar xfz - && cd nettle* && mkdir build && cd build && ../configure --enable-static && make && checkinstall --install --pkgname nettle --pkgversion ${NETTLE_VER} --nodoc && ldconfig
# Building gnutls
ARG GNUTLS_VER
ENV GNUTLS_VER=${GNUTLS_VER:-"3.5.16"}
RUN cd $(mktemp -d) && curl -L "https://www.gnupg.org/ftp/gcrypt/gnutls/v3.5/gnutls-${GNUTLS_VER}.tar.xz" | tar xfJ - && cd gnutls* && mkdir build && cd build && ../configure --disable-shared --enable-static --with-included-libtasn1 --with-included-unistring --without-p11-kit  --disable-hardware-acceleration --disable-padlock && make && checkinstall --install --pkgname gnutls --pkgversion ${GNUTLS_VER} --nodoc && ldconfig
# Building sodium
ARG LIBSODIUM_VER
ENV LIBSODIUM_VER=${LIBSODIUM_VER:-"1.0.5"}
RUN cd $(mktemp -d) && git clone git://github.com/jedisct1/libsodium.git && cd libsodium &&  git checkout tags/${LIBSODIUM_VER} &&  ./autogen.sh &&  ./configure --enable-static && make check && checkinstall --install --pkgname libsodium --pkgversion ${LIBSODIUM_VER} --nodoc && ldconfig
# Building tox

# For c-toxcore pass
ARG TOXSRC
ENV TOXSRC ${TOXSRC:-"TokTok/c-toxcore"}
RUN cd $(mktemp -d) && git clone git://github.com/${TOXSRC}.git c-toxcore && cd c-toxcore &&  autoreconf -i && ./configure --enable-static && make && checkinstall --install --pkgname libtoxcore --pkgversion 1.0.0 --nodoc && ldconfig
